// react/src/components/Global/GlobalComponent.tsx
import { useCount } from "./store";
import { Button } from "./Button";

export function GlobalComponent({ name }: { name: string }) {
  const [count] = useCount();

  return (
    <div className="card">
      <h3>
        {name} Global Component: {count}
      </h3>

      <Button />
    </div>
  );
}

// vue/src/components/GlobalComponent.vue
<script setup lang="ts">
import { store } from "./store";

defineProps<{ name: string }>();

const updateCount = () => {
  store.count++;
};
</script>

<template>
  <div className="card">
    GlobalComponent: {{ name }}
    <div>{{ store.count }}</div>
    <button @click="updateCount">
      Increment <strong>global</strong> count
    </button>
  </div>
</template>
