// react/src/components/Local/LocalState.tsx
import { useState } from "react";
import { ChildOne } from "./ChildOne";
import { ChildTwo } from "./ChildTwo";
import { GlobalComponent } from "../Global/GlobalComponent";

export function Local() {
  const [count, setCount] = useState(0);

  const incrementCount = () => {
    setCount((count) => count + 1);
  };

  return (
    <div className="card">
      <h2>Parent ➡️ Child State: {count}</h2>

      <button onClick={() => setCount((count) => count + 1)}>
        Increment count
      </button>

      <ChildOne count={count} incrementCount={incrementCount} />
      <ChildTwo count={count} incrementCount={incrementCount} />
      <GlobalComponent name="🔵" />
    </div>
  );
}

// vue/src/components/LocalState.vue
<script setup lang="ts">
import ChildOne from "./ChildOne.vue";
import ChildTwo from "./ChildTwo.vue";
import GlobalComponent from "./GlobalComponent.vue";
import { ref } from "vue";

const count = ref(0);

// update count
const updateCount = () => {
  count.value++;
};
</script>

<template>
  <div class="card">
    <h2>Parent ➡️ Child State</h2>
    <button type="button" @click="updateCount">
      Increment count: {{ count }}
    </button>

    <ChildOne :count="count" :updateCount="updateCount" />
    <ChildTwo :count="count" :updateCount="updateCount" />
    <GlobalComponent name="🔵" />
  </div>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>
