// vue/src/App.vue
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import LocalState from "./components/Local/LocalState.vue";
import GlobalState from "./components/Global/GlobalState.vue";
import GlobalComponent from "./components/Global/GlobalComponent.vue";
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <h1>Vite + Vue</h1>

  <div class="grid">
    <LocalState />
    <GlobalState />
  </div>
  <GlobalComponent name="🔴" />
</template>

<style scoped>
.logo {
  height: 3em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// react/src/App.tsx
import reactLogo from "./assets/react.svg";
import { Local } from "./components/Local/LocalState";
import { Global } from "./components/Global/GlobalState";
import { GlobalComponent } from "./components/Global/GlobalComponent";

function App() {
  return (
    <div className="App">
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" className="logo" alt="Vite logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>

      <div className="grid">
        <Local />
        <Global />
      </div>
      <GlobalComponent name="🔴" />
    </div>
  );
}

export default App;
