// react/src/components/Local/LocalState.tsx
import { useState } from "react";
import { ChildOne } from "./ChildOne";
import { ChildTwo } from "./ChildTwo";
import { GlobalComponent } from "../Global/GlobalComponent";
import { Button } from "./Button";

export function Local() {
  const [count, setCount] = useState(0);

  const incrementCount = () => {
    setCount((count) => count + 1);
  };

  return (
    <div className="card">
      <h2>Parent ➡️ Child State: {count}</h2>

      <Button incrementCount={incrementCount} />

      <ChildOne count={count} incrementCount={incrementCount} />
      <ChildTwo count={count} incrementCount={incrementCount} />
      <GlobalComponent name="🔵" />
    </div>
  );
}

// vue/src/components/Local/LocalState.vue
<script setup lang="ts">
import ChildOne from "./ChildOne.vue";
import ChildTwo from "./ChildTwo.vue";
import GlobalComponent from "../Global/GlobalComponent.vue";
import Button from "./Button.vue";

import { ref } from "vue";

const count = ref(0);

const incrementCount = () => {
  count.value++;
};
</script>

<template>
  <div class="card">
    <h2>Parent ➡️ Child State: {{ count }}</h2>
    <Button :incrementCount="incrementCount" />

    <ChildOne :count="count" :incrementCount="incrementCount" />
    <ChildTwo :count="count" :incrementCount="incrementCount" />
    <GlobalComponent name="🔵" />
  </div>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>
