// react/src/components/Global/GlobalState.tsx
import { useCount } from "./store";
import { GlobalComponent } from "./GlobalComponent";
import { ComponentOne } from "./ComponentOne";
import { ComponentTwo } from "./ComponentTwo";
import { Button } from "./Button";

export function Global() {
  const [count] = useCount();

  return (
    <div className="card">
      <h2>Global 🌐 State: {count} </h2>
      <Button />
      <ComponentOne />
      <ComponentTwo />
      <GlobalComponent name="🟡" />
    </div>
  );
}

// vue/src/components/Global/GlobalState.vue
<script setup lang="ts">
import { store } from "./store";

import ComponentOne from "./ComponentOne.vue";
import ComponentTwo from "./ComponentTwo.vue";
import GlobalComponent from "./GlobalComponent.vue";
import Button from "./Button.vue";
</script>

<template>
  <div class="card">
    <h2>Global 🌐 State: {{ store.count }}</h2>

    <Button />
    <ComponentOne />
    <ComponentTwo />
    <GlobalComponent name="🟡" />
  </div>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>
